# Generated by Django 3.1.6 on 2021-02-15 09:10

from django.db import migrations, models

#initially creted table for migration

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customerReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('bran_name', models.CharField(max_length=100)),
            ],
        ),
    ]
