# Generated by Django 3.1.6 on 2021-02-15 09:15

from django.db import migrations, models

#adding the additional columns to the database created (initially I forgot to add them so I altered the table using this other migration)

class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='produ_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerreview',
            name='review_data',
            field=models.TextField(default='nokia'),
            preserve_default=False,
        ),
    ]
